/* 영상 목록 — 새 영상은 맨 위에 추가. 데이터는 videos/<id>.js
   id: 파일 이름 · yt: YouTube 영상 ID · title: *별표*로 감싼 부분은 제목에서 강조 */
window.VIDEOS=[
  {id:"hailey-patterns", ch:"헤일리 쌤", ep:"유용한 영어 패턴 1·2", tag:"#패턴", yt:"IIBM5LU6QVI", len:"3:01:59",
   title:"Useful *Patterns* 1·2",
   desc:"미드·영화에서 뽑은 유용한 영어 패턴 26개, 200문장을 헤일리 쌤 교안의 해설과 함께 정리했어요. 패턴 3편은 교안이 나오면 추가할게요."},
  {id:"soritune-bradpitt", ch:"주아쌤 소리튠영어", ep:"브래드 피트 100장면", tag:"#미드영화쉐도잉", yt:"ocgjkX_n3-E", len:"1:15:52",
   title:"Brad Pitt *100* Lines",
   desc:"브래드 피트 영화 속 일상 회화 100문장을 뜻과 쓰는 상황까지 정리했어요. 교안이 없는 영상이라 자막을 보고 직접 정리했고, 핵심 표현은 하이라이트했어요."},
  {id:"soritune-linking", ch:"주아쌤 소리튠영어", ep:"축약·연음 80", tag:"#발음", yt:"YKDGkBAX_18", len:"1:05:11",
   title:"Linking Sounds *80*",
   desc:"미드에서 가장 안 들리는 축약·연음 표현 80개를 소리튠 교안대로 정리했어요. 표현마다 실제로 들리는 소리를 한글로 적었고, 1·2·3 버튼을 누르면 예문을 읽어줘요."},
  {id:"soritune-drama", ch:"주아쌤 소리튠영어", ep:"미드·영화 500장면", tag:"#미드영화쉐도잉", yt:"NlUVGm_gAIs", len:"52:30",
   title:"Top *100* Movie Lines",
   desc:"미드·영화에 가장 많이 나오는 100문장을 소리튠 교안대로 정리했어요. 문장 속 / 는 끊어 읽는 소리블록이고, 영상은 문장마다 실제 장면 약 5개를 이어서 보여줘요."},
  {id:"soritune-travel", ch:"주아쌤 소리튠영어", ep:"해외여행", tag:"#여행영어", yt:"IwI5qkUAIx8", len:"55:06",
   title:"Travel English *100*",
   desc:"해외여행에서 무조건 쓰는 100문장을 소리튠 교안의 표현 TIP, 꺼내 말하기 상황과 함께 정리했어요."},
  {id:"soritune-reaction", ch:"주아쌤 소리튠영어", ep:"리액션", tag:"#미드영화쉐도잉", yt:"Aoax5SPLF6g", len:"30:11",
   title:"Reactions *50*",
   desc:"미드·영화에 가장 많이 나오는 리액션 표현 50개를 소리튠 교안의 대화 예문과 함께 정리했어요. A·B 버튼을 누르면 대사를 읽어줘요."},
  {id:"soritune-smalltalk", ch:"주아쌤 소리튠영어", ep:"스몰토크", tag:"#미드영화쉐도잉", yt:"iBRddnTy2VI", len:"31:04",
   title:"Small Talk *50*",
   desc:"미드·영화 속 스몰토크 표현 50개를 소리튠 교안의 대화 예문과 함께 정리했어요. A·B 버튼을 누르면 대사를 읽어줘요."},
  {id:"chd-comparison", ch:"Call Her Daddy", ep:"Sunday Session", tag:"#Friendship", yt:"4Nx7UA4IPgk", len:"54:04",
   title:"How *Comparison* Ruins Friendships",
   desc:"알렉스 쿠퍼가 친구의 기쁜 소식을 축하해주지 못하는 관계에 대해 이야기한 에피소드를 문장 단위로 정리했어요. 광고 구간은 뺐어요."},
  {id:"nyc-apartment", ch:"Ryan Nakajima", ep:"NYC Apartment Hunting", tag:"#StreetEasy", yt:"CujJfp64AZw", len:"10:16",
   title:"Studio, *$3,500* and Under",
   desc:"뉴욕에서 월세 3,500달러 이하 스튜디오를 보러 다닌 브이로그를 문장 단위로 정리했어요."},
  {id:"tablo-40", ch:"Hey Tablo", ep:"Ep.40", tag:"#LifeAdvice", yt:"v85gWD_7MCY", len:"50:41",
   title:"My Future is *Cooked!* Help!",
   desc:"타블로의 인생 상담 에피소드를 문장 단위로 정리했어요."}
];
